swagger: "2.0"
info:
  description: API to manage events.
  version: 1.0.0
  title: middleware/example
  contact:
    name: Justine Bachelard.
    email: justine.bachelard@ext.uca.fr
basePath: /
schemes:
  - http
paths:
  /events:
    get:
      tags:
        - events
      summary: Get events.
      description: Get events.
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Event'
        500:
          description: Something went wrong
  /events/{id}:
    get:
      tags:
        - events
      summary: Get a collection.
      description: Get a collection.
      parameters:
        - name: id
          in: path
          description: Collection UUID formatted ID
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Event'
        422:
          description: Cannot parse id
        500:
          description: Something went wrong
definitions:
  Event:
    type: object
    properties:
      Id:
        type: string
      Dtstamp:
        type: string
      Dtstart:
        type: string
      Dtend:
        type: string
      Description:
        type: string
      Location:
        type: string
      Created:
        type: string
      LastModified:
        type: string
      ResourceID:
        type: string